### PR TITLE
A bit of cleanup

### PR DESCRIPTION
**Pull request by stephenstubbs**
Hi, So I've done a bit of cleanup. We will start running staging tomorrow either with the release if you think it's ready. Otherwise just master for now. 

I'll be busy for the next few weeks as we will be converting all our deployments that use postgres to to use this.

So in terms of this project I will be using the pgbouncer_with_vault example and then for our other deployments will be based on permissions with vault to get credentials.

Like you say the pgbouncer examples will probably be moved out into a separate chart or repo using another chart but just want you to know what I'll be testing.

In a few weeks to a month once this is all done I will finish the benchmarking.

Let me know if there is anything you would like me to do. Otherwise I will probably be quite quiet until then.

### CODE REVIEW

**Comment by stephenstubbs** [comment]
After I'm done with the benchmarking for one chart. I will then create a separate script that iterates over all chart names and runs tests and a similar script for benchmarks.

**Comment by LamaAni** [comment]
Actually this comes at a good time. I am very busy. There are only a few minor things I would add if its possible,

1. If you could update the readme that will allow me to release a version.
2. I recommend using a specific release version, either with a tag or the release url as in the examples, to go to staging or prod. 

I must say  I am very happy that you are using this in prod, and would ask that you post any bugs you find so I can fix them. If you could also record the user load (without specifics of course) that would be amazing. 

Lastly, I will start a user experience issue and would love it if you could post there.

**Review by LamaAni — APPROVED** [review]

**Comment by LamaAni** [comment]
So many spelling mistakes... I need to check my code spell checker over here :)

**Comment by LamaAni** [comment]
Location for adding your use case.

https://github.com/LamaAni/postgres-xl-helm/issues/51

**Comment by stephenstubbs** [comment]
Haha yes I sometimes am too focused on the code to look at spelling too. :)

Always nice to have more than one set of eyes on something. 

Sure as soon as it's all up and running I'll get you some data and add to the user experience issue.

Will look at the readme this evening. Sorry I missed it. Anything particular you want me to add?

**Comment by LamaAni** [comment]
A few for the readme,
1. Your examples and experimental need a readme to say how to use and what its about. Please make sure to add an experimental warning.
2. The main readme needs updating, grammer checks and general mistakes in my english. I can add the updates also, but the grammer stuff is harder for me. 
3. Same as the main, if possible, for the examples. 

Thank you, that would help a lot!

**Comment by stephenstubbs** [comment]
ok I've done this now. Will check it one more time and create a separate pull request for it.

**Pull request merged**
