### PR TITLE
initial benchmarks done

### PR DESCRIPTION
**Pull request by stephenstubbs**
Here is my initial go at benchmarks. They are working. I am getting these two errors though which I've posted but results are being generated.
https://github.com/gregs1104/pgbench-tools/issues/22
https://github.com/gregs1104/pgbench-tools/issues/21

### CODE REVIEW

**Comment by LamaAni** [comment]
Awesome. I will check this asap. we are doing a version at work so things might be busy for a bit.

**Comment by LamaAni** [comment]
I have not used pg_bench in the past, so forgive me if there are any major conceptual errors that I am missing here, sadly I cannot right now dive into that. 

That said, I think the benchmarks need more separation of concerns. Each part of the benchmark should be appended with a readme file to see what its benchmarking, something along the lines of https://severalnines.com/blog/benchmarking-postgresql-performance

In general we need to define specific folders for specific jobs under the benchmark, each addressing a specific task we need to check (on kubernetes for specific machine specs). for example, if these apply,
1. Copy into postgres (csv import).
2. Create table index.
3. Join on table.
4. Select on indexed column.
5. Select on non indexed column. 

Also, for these, for each item we need to compare, given a specific set of machine values, the pg vs pgxl. Finally, we must make sure we are using the power of pgxl, that is that all tables are distributed. 

I am not sure how much pg_bench covers here, but these are the most important when considering operations for multiple users.

**Comment by stephenstubbs** [comment]
ok makes sense. I'll look at this in a few weeks and get it done.

**Review by LamaAni — CHANGES_REQUESTED** [review]
As noted in conversation

**Pull request closed without merging**
