### PR TITLE
Changed repo name to postgres-xl-helm

### PR DESCRIPTION
**Pull request by LamaAni**
What:

Changed repo name to better describe the purpose of the repo.

### CODE REVIEW

**Review by stephenstubbs — APPROVED** [review]
I've tested all deployments and it's still working well.

**Comment by stephenstubbs** [comment]
Also let me know if you want me to start merging prs or if you just want me to approve them. Currently it's showing that same issue you told me about before for this pr. Merging is blocked The base branch requires all commits to be signed.

**Comment by LamaAni** [comment]
Basically I prefer that everyone commits their own prs. I think it's a bit more useful because then you can catch any errors "just in time". 

Plus I think it's a bit more polite :)

I fixed the gpg config and now this signed issue should be over. I must apply this since this is a public repo.

**Comment by stephenstubbs** [comment]
OK that makes sense.

**Pull request merged**
