### PR TITLE
move pgbouncer into a new directory

### PR DESCRIPTION
**Pull request by stephenstubbs**
I've moved pgbouncer into a separate folder. So hopefully it's now quite clear whats going on. Only things left for me to do at some point are a bit more cleanup and remove those two sleep commands from the install.sh as it will be a bit more involved than kubectl wait. For the timebeing I will just do the bash scripts for testing and benchmarking. Should have them later today or tomorrow. After running a bit of testing I will hopefully have this running on our staging cluster.

So happy with this so far. Such an incredible project if you think about it.

### CODE REVIEW

**Comment by LamaAni** [comment]
Hi, 

Notice that you are committing this code into the wrong branch. It should be commited into master.

Best
Zav

**Comment by stephenstubbs** [comment]
I'm commiting this to the add_init_scripts branch as it needs what you have added there for it to work.

**Comment by stephenstubbs** [comment]
So once the init scripts issue is sorted out and merged to master the pgbouncer with vault should work 100% I will be using this branch for the benchmarks until that's done which isn't a problem so no rush from my end.

**Comment by LamaAni** [comment]
I see.

I don't think we should do that. It's bad practice. 

Best would be to leave the PR open and merge them one after the other. That way we do not mix dependencies and allow good revert procedure in case that is needed.

I'll separate them.

**Comment by stephenstubbs** [comment]
ah ok sorry about that

**Comment by LamaAni** [comment]
It's ok it happens. I need to write these down also so it's a bit on me.

**Pull request merged**
