### PR TITLE
initial tests done for transient

### PR DESCRIPTION
**Pull request by stephenstubbs**
I have created tests and it is working. The idea I had for this was that another script will iterate over a list of chart names and then pass them to this so it can run on all deployment examples but I first want this to be right.

Working fine except one small issue. It might be related to the issue with the init scripts.

It still needs a few seconds even after all the containers are ready with this.

`kubectl wait --for=condition=ready pod -l "app=${CHART_NAME}-postgres-xl" --timeout=60s`

So I have added 

`sleep 5`

### CODE REVIEW

**Comment by LamaAni** [comment]
It might be a few days, but I will test this and how to remove the sleep. 

I will also check for a dry run mode in helm to allow us to validate the tank without actually creating the pods.

**Comment by stephenstubbs** [comment]
Ok great thanks. One more thing I did try kubectl wait with services but they dont have ready status so it doesn't work. https://github.com/kubernetes/kubernetes/issues/80828

**Comment by stephenstubbs** [comment]
I have messed up. I deleted my fork and created a new one for the new pr I have done for adding pgbouncer with init scripts. From now on I will just keep the same fork and and keep it in sync with yours and do each pr in a different branch on my fork as it should be. When contributing to open source software in the past I have just done this as it's usually a one off. Hopefully this is the last time there is an issue like this. Sorry about this.

**Comment by LamaAni** [comment]
It OK it happends. I am out for the weekend but I will check this as soon as I can.

**Comment by LamaAni** [comment]
This is a very nice approach. I think the whole kubectl to exec a query as a test is very good. 
I think that for the basic current implementation this is well enough.

I might reorder some stuff but this is a good start.

**Review by LamaAni — APPROVED** [review]

**Comment by stephenstubbs** [comment]
ok great.

**Pull request merged**
